
version: '3.8'

volumes:
  neo4j-data:

services:
  neo4j:
    image: neo4j:4.2-enterprise
    container_name: neo4j
    restart: unless-stopped
    ports:
      - 7474:7474 # HTTP
      - 7687:7687 # Bolt
    environment:
      - NEO4J_AUTH=none
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    volumes:
      - neo4j-data:/data

  pyclient:
    container_name: pyclient
    build: ./python-client/
